# Generated by Django 4.1.5 on 2023-01-30 15:16

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=wagtail.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
